name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
      - uses: lukka/get-cmake@3.10

      - name: Create build directory
        run: mkdir build

      - name: Change to build directory
        run: cd build

      - name: Configure with CMake
        run: cmake ..

      - name: Build with make
        run: make
