name: Makefile CI

defaults:
  run:
    working-directory: ./
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Change Directory
      run: cd src
    - name: where
      run: ls
    - name: Build
      run: make
